name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '56 5 * * *'

jobs:

  testsuite:
    name: all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1' ]
        TYPO3: [ '11', '12' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -s composerInstall

      - name: Acceptance Tests with content_defender
        if: matrix.TYPO3 != '13'
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -s acceptance -e --fail-fast

      - name: Acceptance Tests v13
        if: matrix.TYPO3 == '13'
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -s acceptance -e "--fail-fast --skip-group=content_defender"

      - name: Archive acceptance tests results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: acceptance-test-reports-${{ matrix.php }}-${{ matrix.TYPO3 }}
          path: .Build/Web/typo3temp/var/tests/_output
